### PR TITLE
New ui

### PR DESCRIPTION
**Pull request by mvanlaar**
I here by create a pull request for a new ui. It's based on the version 3.4.3. And adds new features and fixes some bugs allong the way.

**Fixes:** 
#152 
#145 (Added tooltip)
#144 
#120 (shapes.html can be used to generate shapes based on online and drawing)
#92 
#32 (partly allow delete stop in trip)
#8 (It works in edge, Firefox and chrome)
#5 

**New:**
#110 
#88 (Based on Openstreetmap)
#64 (Possible to set your own layers as background)
#52 (Possible to import in shapes.html based on gpx, kml and geojson)
#14 

**Feature:**
#90 (Possibility to create config page with json backend) 
#21 (Allow importing stops from csv, openstreetmap and kml files)
#15 (see shapes.html)

It will contain bugs. But it would like to submit it now.
@answerquest

### CODE REVIEW

**Comment by answerquest** [comment]
Hi Martin,

Great stuff! I'll go over this in the weekend.

**Comment by answerquest** [comment]
@mvanlaar I had made these changes after your fork:

https://github.com/WRI-Cities/static-GTFS-manager/pull/153/files#diff-5f1e81a3a8ca836b2760104dab928c50

**Comment by answerquest** [comment]
@mvanlaar I don't have experience with merging changes, can you help? See this:

https://github.com/WRI-Cities/static-GTFS-manager/pull/153/files#diff-5f1e81a3a8ca836b2760104dab928c50

But I had already done that change, it's coming here again because your PR is relative to an older version?

**Comment by answerquest** [comment]
@mvanlaar ok I'm realising you probably saw and reflected the change at your end too.

I finally figured how to download your branch to my laptop and give it a spin. Sharing the command line for others...
```
git clone -b new-ui --single-branch https://github.com/mvanlaar/static-GTFS-manager.git
```
I want to create a new branch in this repo with this PR and work on things further (as you mentioned, there's some places needing attention). Instead of merging it with master branch right away. Would you know how to go about that?

**Comment by mvanlaar** [comment]
I think you have to create new branch and pull in my branch.

**Comment by answerquest** [comment]
Whew, finally did it! Had a snafu 2 days ago : I resolved all the conflicts, then wanted to check something out and forgot to press the big green button to commit all the changes. Had to do it all over again. I've pushed this PR into a newly created branch "v4.0.0" instead of master. So we can work further on this branch and resolve the loose ends before making it the master.

**Pull request merged**
